apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 7
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        work_type: infra
      containers:
        - name: inflate
          image: viktoruj/ping_pong
          resources:
            requests:
              cpu: 1
